import math
'''
    Class: Action

    Enumeration of possible robot actions.
    The change in pose generated by each action is
    a tuple of (linear, angular) change.

'''
class Action:
    LEFT = -1
    FORWARD = 0
    RIGHT = 1

    ACTION_MAP = {  # action : (linear, angular)
        LEFT:(0, math.radians(10)),
        FORWARD:(5, 0),
        RIGHT:(0, math.radians(-10))
    }

    '''
        Function: get_pose_change
        Input: Action action

        Returns the linear and angular change in pose.
        If no movement for an action is defined, returns (0, 0).

    '''
    @staticmethod
    def get_pose_change(action):
        return Action.ACTION_MAP.get(action, (0, 0))

    @staticmethod
    def get_all_actions():
        return Action.ACTION_MAP.keys()
